#!/usr/bin/env bash
# ============================================================
#  setup.sh — Stake Dice Bot VPS Setup
#  Supported: Ubuntu 20.04/22.04/24.04, Debian 11/12
# ============================================================
set -euo pipefail

# ── Colours ─────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
ok()      { echo -e "${GREEN}[ OK ]${RESET}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERR ]${RESET}  $*" >&2; }
banner()  { echo -e "\n${BOLD}${CYAN}══════════════════════════════════════════${RESET}"; \
             echo -e "${BOLD}${CYAN}  $*${RESET}"; \
             echo -e "${BOLD}${CYAN}══════════════════════════════════════════${RESET}\n"; }

# ── Paths ────────────────────────────────────────────────────
INSTALL_DIR="${HOME}/stake-dice-bot"
ENV_FILE="${INSTALL_DIR}/.env"
SERVICE_NAME="stake-dice-bot"
VENV_DIR="${INSTALL_DIR}/venv"

banner "Stake Dice Bot — VPS Setup"

# ── 1. System dependencies ───────────────────────────────────
info "Updating package list..."
sudo apt-get update -qq

info "Installing Python 3, pip, venv, screen..."
sudo apt-get install -y -qq python3 python3-pip python3-venv screen curl
ok "System packages ready."

# ── 2. Project directory ─────────────────────────────────────
info "Setting up project directory: ${INSTALL_DIR}"
mkdir -p "${INSTALL_DIR}"

# Copy bot file if running from source directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${SCRIPT_DIR}/dice_bot.py" ]]; then
    cp "${SCRIPT_DIR}/dice_bot.py" "${INSTALL_DIR}/dice_bot.py"
    ok "Copied dice_bot.py → ${INSTALL_DIR}"
else
    warn "dice_bot.py not found next to setup.sh."
    warn "Please copy dice_bot.py to ${INSTALL_DIR} manually before running the bot."
fi

# ── 3. Python virtual environment ───────────────────────────
info "Creating Python virtual environment..."
python3 -m venv "${VENV_DIR}"
"${VENV_DIR}/bin/pip" install --quiet --upgrade pip
"${VENV_DIR}/bin/pip" install --quiet requests
ok "Virtual environment ready: ${VENV_DIR}"

# ── 4. Stake API token setup ─────────────────────────────────
banner "Stake API Token Setup"

echo -e "${YELLOW}How to get your Stake API token:${RESET}"
echo -e "  1. Login to Stake.com in your browser"
echo -e "  2. Open DevTools (F12) → Application → Cookies"
echo -e "  3. Find the cookie named  ${BOLD}x-access-token${RESET}  and copy its value"
echo -e "  4. Or: DevTools → Network tab → any GraphQL request → Headers → ${BOLD}x-access-token${RESET}\n"

# Check if .env already exists
EXISTING_TOKEN=""
if [[ -f "${ENV_FILE}" ]]; then
    EXISTING_TOKEN=$(grep -E "^STAKE_API_KEY=" "${ENV_FILE}" 2>/dev/null | cut -d'=' -f2- || true)
fi

if [[ -n "${EXISTING_TOKEN}" ]]; then
    warn "An API token is already saved in ${ENV_FILE}"
    read -r -p "  Replace it with a new token? [y/N]: " REPLACE
    if [[ ! "${REPLACE}" =~ ^[Yy]$ ]]; then
        ok "Keeping existing token."
        TOKEN="${EXISTING_TOKEN}"
    else
        EXISTING_TOKEN=""
    fi
fi

if [[ -z "${EXISTING_TOKEN}" ]]; then
    while true; do
        read -r -s -p "  Paste your Stake API token (input hidden): " TOKEN
        echo
        if [[ -z "${TOKEN}" ]]; then
            error "Token cannot be empty. Try again."
        elif [[ ${#TOKEN} -lt 20 ]]; then
            error "Token looks too short (${#TOKEN} chars). Check and try again."
        else
            break
        fi
    done

    # Write .env
    cat > "${ENV_FILE}" <<EOF
# Stake Dice Bot — Environment Variables
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
STAKE_API_KEY=${TOKEN}
EOF
    chmod 600 "${ENV_FILE}"
    ok "Token saved to ${ENV_FILE} (permissions: 600)"
fi

# ── 5. Validate token against Stake API ──────────────────────
info "Validating token against Stake API..."
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
    -X POST "https://api.stake.com/graphql" \
    -H "Content-Type: application/json" \
    -H "x-access-token: ${TOKEN}" \
    --data '{"query":"{ user { id name } }"}' \
    --max-time 10 || echo "000")

case "${HTTP_STATUS}" in
    200)
        ok "Token is valid — Stake API responded with HTTP 200."
        ;;
    401)
        error "HTTP 401 — Token is invalid or expired. Update it in ${ENV_FILE}"
        warn "You can still proceed, but the bot will fail to place bets until the token is fixed."
        ;;
    000)
        warn "Could not reach Stake API (timeout / DNS). Check your VPS internet connection."
        ;;
    *)
        warn "Stake API returned HTTP ${HTTP_STATUS}. Proceeding anyway."
        ;;
esac

# ── 6. Launch wrapper script ─────────────────────────────────
LAUNCHER="${INSTALL_DIR}/run_bot.sh"
cat > "${LAUNCHER}" <<'RUNSCRIPT'
#!/usr/bin/env bash
# run_bot.sh — loads .env and starts the dice bot
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ -f "${DIR}/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "${DIR}/.env"
    set +a
else
    echo "[ERROR] .env file not found at ${DIR}/.env"
    exit 1
fi

exec "${DIR}/venv/bin/python" "${DIR}/dice_bot.py"
RUNSCRIPT
chmod +x "${LAUNCHER}"
ok "Launcher created: ${LAUNCHER}"

# ── 7. Systemd service (optional) ────────────────────────────
banner "Service Setup (optional)"
read -r -p "  Install as a systemd service (auto-start on reboot)? [y/N]: " INSTALL_SERVICE

if [[ "${INSTALL_SERVICE}" =~ ^[Yy]$ ]]; then
    SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
    sudo tee "${SERVICE_FILE}" > /dev/null <<SERVICEFILE
[Unit]
Description=Stake Dice Bot (IDR)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${USER}
WorkingDirectory=${INSTALL_DIR}
ExecStart=${LAUNCHER}
EnvironmentFile=${ENV_FILE}
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SERVICEFILE

    sudo systemctl daemon-reload
    sudo systemctl enable "${SERVICE_NAME}"
    ok "Systemd service installed: ${SERVICE_NAME}"
    echo
    echo -e "  ${BOLD}Service commands:${RESET}"
    echo -e "    Start  :  sudo systemctl start  ${SERVICE_NAME}"
    echo -e "    Stop   :  sudo systemctl stop   ${SERVICE_NAME}"
    echo -e "    Status :  sudo systemctl status ${SERVICE_NAME}"
    echo -e "    Logs   :  journalctl -fu         ${SERVICE_NAME}"
else
    ok "Skipping systemd service."
fi

# ── 8. Screen helper (manual run) ────────────────────────────
SCREEN_HELPER="${INSTALL_DIR}/start_screen.sh"
cat > "${SCREEN_HELPER}" <<SCREENSCRIPT
#!/usr/bin/env bash
# Starts the bot inside a detached screen session so it keeps running
# after you close SSH.  Use 'screen -r stake-bot' to reattach.
screen -dmS stake-bot bash -c "${LAUNCHER}; exec bash"
echo "Bot started in screen session 'stake-bot'."
echo "Reattach with:  screen -r stake-bot"
echo "Detach again :  Ctrl+A then D"
SCREENSCRIPT
chmod +x "${SCREEN_HELPER}"
ok "Screen helper created: ${SCREEN_HELPER}"

# ── 9. Token update helper ───────────────────────────────────
UPDATE_TOKEN="${INSTALL_DIR}/update_token.sh"
cat > "${UPDATE_TOKEN}" <<'TOKENSCRIPT'
#!/usr/bin/env bash
# update_token.sh — quickly replace the Stake API token
set -euo pipefail
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.env"

echo "Paste your new Stake API token (input hidden):"
read -r -s NEW_TOKEN
echo

if [[ -z "${NEW_TOKEN}" ]]; then
    echo "[ERROR] Token cannot be empty." >&2
    exit 1
fi

if grep -q "^STAKE_API_KEY=" "${ENV_FILE}" 2>/dev/null; then
    sed -i "s|^STAKE_API_KEY=.*|STAKE_API_KEY=${NEW_TOKEN}|" "${ENV_FILE}"
else
    echo "STAKE_API_KEY=${NEW_TOKEN}" >> "${ENV_FILE}"
fi

chmod 600 "${ENV_FILE}"
echo "[OK] Token updated in ${ENV_FILE}"
echo "     Restart the bot for the change to take effect."
TOKENSCRIPT
chmod +x "${UPDATE_TOKEN}"
ok "Token updater created: ${UPDATE_TOKEN}"

# ── 10. Summary ──────────────────────────────────────────────
banner "Setup Complete"

echo -e "  ${BOLD}Install directory :${RESET} ${INSTALL_DIR}"
echo -e "  ${BOLD}Bot script        :${RESET} ${INSTALL_DIR}/dice_bot.py"
echo -e "  ${BOLD}Token file        :${RESET} ${ENV_FILE}"
echo
echo -e "  ${BOLD}Run manually (foreground):${RESET}"
echo -e "    cd ${INSTALL_DIR} && ./run_bot.sh"
echo
echo -e "  ${BOLD}Run in background (screen):${RESET}"
echo -e "    ${INSTALL_DIR}/start_screen.sh"
echo -e "    screen -r stake-bot   # reattach"
echo
echo -e "  ${BOLD}Update token later:${RESET}"
echo -e "    ${INSTALL_DIR}/update_token.sh"
echo

if [[ "${INSTALL_SERVICE}" =~ ^[Yy]$ ]]; then
    echo -e "  ${BOLD}Start service:${RESET}"
    echo -e "    sudo systemctl start ${SERVICE_NAME}"
    echo
fi

echo -e "${GREEN}${BOLD}Ready. Run the bot and monitor its output.${RESET}\n"
